from gunicorn import http as http
from gunicorn import sock as sock
from gunicorn import util as util
from gunicorn.http import wsgi as wsgi
from gunicorn.sock import TCPSocket as TCPSocket
from gunicorn.workers import base as base

class StopWaiting(Exception): ...

class SyncWorker(base.Worker):
    def accept(self, listener: TCPSocket): ...
    def wait(self, timeout: float): ...
    def is_parent_alive(self) -> bool: ...
    def run_for_one(self, timeout: float): ...
    def run_for_multiple(self, timeout) -> None: ...
    def run(self) -> None: ...
    def handle(self, listener, client, addr) -> None: ...
    alive: bool
    def handle_request(self, listener, req, client, addr) -> None: ...
