import socket

from _typeshed import Incomplete

from gunicorn import util
from gunicorn.http import Message
from gunicorn.workers import base

class StopWaiting(Exception): ...

class SyncWorker(base.Worker):
    def accept(self, listener: socket.socket) -> Incomplete: ...
    def wait(self, timeout: float) -> Incomplete: ...
    def is_parent_alive(self) -> bool: ...
    def run_for_one(self, timeout: float) -> Incomplete: ...
    def run_for_multiple(self, timeout: float) -> None: ...
    def run(self) -> None: ...
    def handle(
        self, listener: socket.socket, client: Incomplete, addr: Incomplete
    ) -> None: ...
    alive: bool
    def handle_request(
        self,
        listener: socket.socket,
        req: Message,
        client: Incomplete,
        addr: Incomplete,
    ) -> None: ...
