from _typeshed import Incomplete

class Spew:
    trace_names: Incomplete
    show_values: Incomplete
    def __init__(self, trace_names: Incomplete | None = ..., show_values: bool = ...) -> None: ...
    def __call__(self, frame, event, arg): ...

def spew(trace_names: Incomplete | None = ..., show_values: bool = ...) -> None: ...
def unspew() -> None: ...
