from typing_extensions import Never

class Unsupported(RuntimeError): ...

def set_owner_process(
    uid: int | None, gid: int | None, initgroups: bool = ...
) -> Never: ...
def close_on_exec(fd: int) -> None: ...
def resolve_uid(val: str) -> Never: ...
def resolve_gid(val: str) -> Never: ...
def pipe2() -> Never: ...
def matching_effective_uid_gid(uid: int | None, gid: int | None) -> bool: ...

ALL = [
    "close_on_exec",
    "matching_effective_uid_gid",
    "pipe2",
    "resolve_gid",
    "resolve_uid",
    "set_owner_process",
]
