import socket
from collections.abc import Iterator
from typing import Optional

from _typeshed import Incomplete

class Unreader:
    buf: Incomplete
    def __init__(self) -> None: ...
    def chunk(self) -> bytes: ...
    def read(self, size: int | None = ...) -> bytes: ...
    def unread(self, data: bytes) -> None: ...

class SocketUnreader(Unreader):
    sock: Incomplete
    mxchunk: Incomplete
    def __init__(self, sock: socket.socket, max_chunk: int = ...) -> None: ...
    def chunk(self) -> bytes: ...

class IterUnreader(Unreader):
    iter: Incomplete
    def __init__(self, iterable: Iterator) -> None: ...
    def chunk(self) -> bytes: ...
