name: buildpackage
# Goal: produce .deb files on Ubuntu >= 22.04 (jammy) or Debian >= 12 (bookworm/bullseye-backports)
# https://wiki.debian.org/Packaging
# https://www.debian.org/doc/debian-policy/
# https://www.debian.org/doc/packaging-manuals/python-policy/

# https://docs.github.com/articles/events-that-trigger-workflows
on:
  push:
    tags:
     - '*'
  pull_request:
    # self
    paths:
      - .github/workflows/ubuntu.yml
  workflow_dispatch:
  # https://docs.github.com/articles/configuring-a-workflow#manually-running-a-workflow

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  # note that some tools care only for the name, not the value
  FORCE_COLOR: 1

  # reduce metadata. unlike elsewhere, build artifacts should differ by content only
  SOURCE_DATE_EPOCH: 0

jobs:
  dpkg-buildpackage:
    name: buildpackage-${{ matrix.python-version }}
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
    timeout-minutes: 4
    # https://docs.github.com/articles/virtual-environments-for-github-actions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
      matrix:
        python-version: [ "os-py" ]
    steps:
      - uses: actions/checkout@v4
        with:
          path: source
      - name: prepare deb source dir (workaround)
        # why the incorrect version? because this way we can skip rewrite debian/changelog for now
        run: |
          mkdir --verbose --parents upload/workaround
          mkdir --verbose --parents workaround
          ( cd source/ && git archive --format=tar --prefix=gunicorn-21.2.0/ HEAD | gzip ) > workaround/gunicorn_21.2.0.orig.tar.gz
          ( cd workaround/ && tar --extract --file gunicorn_21.2.0.orig.tar.gz gunicorn-21.2.0 )
          test -s workaround/gunicorn-21.2.0/pyproject.toml
          rsync -vrlt source/.github/packaging/debian/ workaround/gunicorn-21.2.0/debian
          echo 'extend-diff-ignore = "^setup\.cfg$"' > workaround/gunicorn-21.2.0/debian/source/options
          mv --verbose workaround/gunicorn-21.2.0/debian/setup.cfg workaround/gunicorn-21.2.0/
          chmod --changes +x workaround/gunicorn-21.2.0/debian/control
          ls -l workaround/gunicorn-21.2.0/
      - name: prepare deb source dir (clean)
        run: |
          mkdir --verbose --parents upload
          mkdir --verbose --parents debian
          ( cd source/ && git archive --format=tar --prefix=gunicorn-21.2.0/ HEAD | gzip ) > debian/gunicorn_21.2.0.orig.tar.gz
          ( cd debian/ && tar --extract --file gunicorn_21.2.0.orig.tar.gz gunicorn-21.2.0 )
          test -s debian/gunicorn-21.2.0/pyproject.toml
          rsync -vrlt source/.github/packaging/debian/ debian/gunicorn-21.2.0/debian
          chmod --changes +x debian/gunicorn-21.2.0/debian/control
          ls -l debian/gunicorn-21.2.0/
      # ideally, build-dep step would be executed by dkpg scripts
      - name: Install dpkg Dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install dpkg-dev make python3-all quilt debhelper dh-python python3-setuptools pybuild-plugin-pyproject
          # print versions
          apt policy python3-all
          apt policy dh-python
          apt policy python3-setuptools
          apt policy python3-distutils
          apt policy python3-toml
          apt policy python3-tomli
          apt policy python3-setuptools-whl
          apt policy python3-pep517
          apt policy python3-build
          apt policy pybuild-plugin-pyproject
      - name: build deb (workaround)
        run: |
          test -s workaround/gunicorn-21.2.0/pyproject.toml
          test -s workaround/gunicorn-21.2.0/setup.cfg
          test -s workaround/gunicorn-21.2.0/debian/control
          test -d workaround/gunicorn-21.2.0/tests
          ( cd workaround/gunicorn-21.2.0/ && dpkg-buildpackage --unsigned-source --unsigned-changes )
          cp --verbose --archive workaround/*.deb upload/workaround/
      - name: build deb (clean)
        continue-on-error: true
        run: |
          test -s debian/gunicorn-21.2.0/pyproject.toml
          test -s debian/gunicorn-21.2.0/debian/control
          test -d debian/gunicorn-21.2.0/tests
          ( cd debian/gunicorn-21.2.0/ && dpkg-buildpackage --unsigned-source --unsigned-changes )
          cp --verbose --archive debian/*.deb upload/
      - uses: actions/upload-artifact@v3
        with:
          path: upload
          name: dist
