name: lint
on:
  push:
    tags:
     - '*'
  pull_request:
  # on pull, automaric
  workflow_dispatch:
  # allow manual trigger
permissions:
  contents: read # to fetch code (actions/checkout)
env:
  # note that some tools care only for the name, not the value
  FORCE_COLOR: 1
jobs:
  lint:
    name: ${{ matrix.toxenv }} / ${{ matrix.os }} / ${{ matrix.python-version }}
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
    timeout-minutes: 4
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toxenv: [lint, docs-lint, pycodestyle, format, mypy]
        python-version: [ "3.10" ]
        os: ["ubuntu-latest"]
        include:
          - os: windows-latest
            python-version: "3.12"
            toxenv: format
          - os: macos-latest
            python-version: "3.12"
            toxenv: docs-lint
    steps:
      - uses: actions/checkout@v4
      - name: Using Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - run: tox -e ${{ matrix.toxenv }}
