name: ubuntu
on:
  push:
    tags:
     - '*'
  pull_request:
    # self
    paths:
      - .github/workflows/ubuntu.yml
  workflow_dispatch:
  # allow manual trigger

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  # note that some tools care only for the name, not the value
  FORCE_COLOR: 1

jobs:
  lint:
    name: debian-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.x" ]
    steps:
      - uses: actions/checkout@v4
        with:
          path: source
      - name: Using Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
      - name: make dist
        run: |
          # only source tarball:
          # (cd source/ && python -m build --sdist)
          # all:
          (cd source/ && python -m build)
          mkdir -p upload
          cp --archive source/dist/*{.tar.gz,.whl} upload/
      - uses: actions/upload-artifact@v3
        with:
          path: dist
          name: upload
